global:
  scrape_interval: 5s
  scrape_timeout: 4s

  external_labels:
    monitor: 'node-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.207.1:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.207.1:9100']

  - job_name: 'nvidia_gpu_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.207.1:9835']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.207.1:3000']