global:
  scrape_interval: 10s
  scrape_timeout: 5s

  external_labels:
    monitor: 'hpc-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'nvidia_gpu_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9835']

  - job_name: 'dcgm_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9400']

  - job_name: 'grafana'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:3000']
