apiVersion: 1
groups:
    - orgId: 1
      name: B
      folder: rules
      interval: 10s
      rules:
        - uid: b4faa1f3-059b-4563-bbf5-e2c6a9fbc9c2
          title: CPU 온도 알림
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: node_hwmon_temp_celsius{job="node"}
                format: time_series
                hide: false
                instant: false
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B > 85
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          dashboardUid: rYdddlPWk
          panelId: 77
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: rYdddlPWk
            __panelId__: "77"
            description: CPU 온도가 85도 이상 입니다.
            summary: CPU 온도 알림
          isPaused: false
        - uid: eb29d5e8-34ef-49d0-ac3c-8f710fb429c4
          title: "\bGPU 온도 알림"
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: DCGM_FI_DEV_GPU_TEMP{instance="192.168.207.1:9400"}
                format: time_series
                hide: false
                instant: false
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B > 85
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          dashboardUid: rYdddlPWk
          panelId: 77
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: rYdddlPWk
            __panelId__: "77"
            description: GPU 온도가 85도 이상 입니다.
            summary: GPU 온도 알림
          isPaused: false
